global:
  scrape_interval:     10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'api-gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['api-gateway:8080']
        labels:
          application: 'Api-gateway Application'
  - job_name: 'chatroom'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['chatroom:8080']
        labels:
          application: 'Chatroom Service Application'
  - job_name: 'notification'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['notification:8080']
        labels:
          application: 'Notification Service Application'
  - job_name: 'userjob'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['userjob:8080']
        labels:
          application: 'UserJob Service Application'